# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: Maven
        strategy:
          maxParallel: 2
          matrix:
            Vertx:
              location: 'pom.xml'
              goal: '-pl com.ing.cerebro.workshop:reactive-rest-app
              -pl com.ing.cerebro.workshop:delay-client
              -am package'
            Spring:
              location: 'spring-rest-service/pom.xml'
              goal: 'package'
            Reactive-Spring:
              location: 'reactive-spring-rest-service/pom.xml'
              goal: 'package'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: '$(location)'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: '$(goal)'
          - publish: $(System.DefaultWorkingDirectory)
            artifact: $(System.JobName)
  - stage: Containers
    dependsOn: Build
    jobs:
      - job: login
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'cerebro-reg'
              command: 'login'
      - job: ContainerBuild
        dependsOn: login
        strategy:
          maxParallel: 2
          matrix:
            Vertx_REST:
              app_folder: reactive-rest-app
              app_service_name: vertx-rest-service
              download_artifact: Vertx
            Vertx_Delay_Client:
              app_folder: delay-client
              app_service_name: vertx-delay-service
              download_artifact: Vertx
            Spring_REST:
              app_folder: spring-rest-service
              app_service_name: spring-rest-service
              download_artifact: Spring
            Spring_Reactive:
              app_folder: reactive-spring-rest-service
              app_service_name: reactive-spring-rest-service
              download_artifact: Reactive-Spring
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - template: templates/build-image.yml
  - stage: Helm
    dependsOn: Build
    jobs:
      - job: Template
        strategy:
          maxParallel: 2
          matrix:
            Vertx_REST:
              app_folder: reactive-rest-app
              app_service_name: vertx-rest-service
              download_artifact: Vertx
            Vertx_Delay_Client:
              app_folder: delay-client
              app_service_name: vertx-delay-service
              download_artifact: Vertx
            Spring_REST:
              app_folder: spring-rest-service
              app_service_name: spring-rest-service
              download_artifact: Spring
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: templates/create-helm-files.yml