apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "reactive-spring-rest-service.fullname" . }}
  labels:
{{ include "reactive-spring-rest-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "reactive-spring-rest-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
