apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "vertx-rest-service.fullname" . }}-config
  labels:
{{ include "vertx-rest-service.labels" . | indent 4 }}
data:
{{ include "vertx-rest-service.config" . | indent 2 }}