apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "vertx-rest-service.fullname" . }}-config
  labels:
{{ include "vertx-rest-service.labels" . | indent 4 }}
data:
  server.port: {{ .Values.image.port }}
  client.host: '{{.Release.Name}}-vertx-client-service'
  client.port: 80