apiVersion: v1
kind: Service
metadata:
  namespace: reactive-workshop
  name: hazelcast-eventbus
  labels:
    hazelcast-cluster: "true"
spec:
  type: ClusterIP
  ports:
    - port: 5701
      name: hazelcast
      targetPort: hazelcast
  selector:
    hazelcast-cluster: "true"
    application-type: vertx
