apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "spring-rest-service.fullname" . }}
  labels:
{{ include "spring-rest-service.labels" . | indent 4 }}
data:
{{ include "spring-rest-service.config" . | indent 2 }}