apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "vertx-delay-service.fullname" . }}-config
  labels:
{{ include "vertx-delay-service.labels" . | indent 4 }}
data:
  server.port: '{{ .Values.image.port }}'
