apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "vertx-delay-service.fullname" . }}
  labels:
{{ include "vertx-delay-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vertx-delay-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vertx-delay-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        hazelcast-cluster: "true"
        application-type: vertx
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "vertx-delay-service.fullname" . }}-config
          env:
            - name: release
              value: {{.Release.Name}}
            - name: configName
              value: {{ include "vertx-delay-service.fullname" . }}-config
            - name: HAZELCAST_SERVICE_NAME
              value: {{ include "vertx-delay-service.fullname" . }}-hazelcast
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{.Values.image.port}}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.hazelcast.port }}
          livenessProbe:
            httpGet:
              path: /client/1
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readiness.delay }}
            httpGet:
              path: /client/1
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Values.service_accounts.hazelcast.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
